import Head from 'next/head'
import { ReactElement } from 'react'

import styles from '../styles/Home.module.css'

export default function Home(): ReactElement {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Project Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>NextJS Application</h1>
        <h2>Boilerplate</h2>

        <h3>Technologies</h3>
        <p>
          This project has <strong>Editorconfig</strong>,{' '}
          <strong>Eslint</strong>, <strong>Prettier</strong>,{' '}
          <strong>Commitlint</strong>, <strong>Commitizen</strong> and{' '}
          <strong>Husky</strong> setup.
        </p>

        <h3>Public Secrets</h3>
        <p>
          NODE_ENV: <strong>{process.env.NODE_ENV}</strong>
        </p>
      </main>
    </div>
  )
}
